[project]
name = "berlinbikewatchde"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.86",
    "confluent-kafka>=2.15.0",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "redshift-connector>=2.1.16",
    "requests>=2.34.2",
    "streamlit>=1.63.0",
    "tzdata>=2026.3",
]
